# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-22 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_remove_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pro_pic',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
