# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-22 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_userprofile_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pro_pic',
            field=models.ImageField(blank=True, upload_to='media/profilepic'),
        ),
    ]
