# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-23 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20171123_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='bookpic'),
        ),
    ]
