# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-24 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_userlibrary_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlibrary',
            old_name='link',
            new_name='user',
        ),
    ]
