# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-24 17:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20171124_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL),
        ),
    ]
