# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-27 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20171128_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='isFavorite',
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
    ]
