# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_auto_20180111_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='book_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.UserLibrary'),
            preserve_default=False,
        ),
    ]
